project:
  type: website
  output-dir: docs
  pre-render:
    - scripts/make_thumbs.R

website:
  title: "Cori Lopazanski"
  navbar:
    left:
      - href: index.qmd
        text: About
      - publications.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

